# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Executes unit tests"
  lane :tests do
    # Clean derived data
    clear_derived_data
    
    # Run tests with CI-specific settings
    run_tests(
      scheme: "MedalsAT",
      clean: true,
      derived_data_path: "./derived_data",
      output_directory: "./test_results",
      build_for_testing: true,
      disable_package_automatic_updates: false,
      skip_package_dependencies_resolution: false,
      xcargs: "CI=true"
    )
  end
end