# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Executes unit tests"
  lane :tests do
  # Common scheme names
  possible_schemes = [
    "MedalsAT"
  ]
  
  # Try each scheme until one works
  possible_schemes.each do |scheme|
    begin
      UI.message("Trying scheme: #{scheme}")
      scan(
        scheme: scheme,
        project: "MedalsAT.xcodeproj",
        device: "iPhone 17 Pro"
      )
     end
    end
  end
end